// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Mohammed Maruff (Esan Maruff) <esan@etamil.in>
//! The folder `etamil --artino` writes: everything `arduino-cli` needs to link
//! and upload a compiled program.
//!
//! ```text
//! <out>/<sketch>/<sketch>/<sketch>.ino     setup() and loop() call the program
//! <out>/<sketch>/<sketch>/artino.h         the runtime (MIT)
//! <out>/<sketch>/<sketch>/artino_rt.cpp
//! <out>/<sketch>/libraries/artino_prog/library.properties      precompiled=true
//! <out>/<sketch>/libraries/artino_prog/src/artino_prog.h
//! <out>/<sketch>/libraries/artino_prog/src/<mcu>/libartino_prog.a   what LLVM built
//! ```
//!
//! then `arduino-cli compile --fqbn <fqbn> --libraries <out>/<sketch>/libraries <out>/<sketch>/<sketch>`.
//!
//! Each program has its own `libraries`, because every compiled program is a
//! library called artino_prog: two sketches sharing one folder would share one
//! program, and the one built second would silently be the one both ran.
//!
//! The archive is written here rather than by `ar`: it holds one object and
//! its index names two symbols, both known in advance, and a compiler that
//! needed binutils beside it to finish a build would not be finished.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use super::manifest::{self, Manifest};
use super::{Board, RUNTIME_HEADER, RUNTIME_SOURCE};

/// What the sketch needs to know about the object it wraps.
pub struct Compiled {
    /// Every report site's text, by number, for `artino_sites.txt`.
    pub sites: Vec<String>,
    /// The program makes a tone: only then is the core's Tone linked, whose
    /// timer interrupt would otherwise cost every AVR sketch its flash.
    pub tone: bool,
}

/// The symbols the program exports to the sketch.
pub const EXPORTS: &[&str] = &["artino_setup", "artino_loop"];

const LIBRARY_PROPERTIES: &str = "name=artino_prog
version=0.1.0
author=eTamil artino
maintainer=eTamil artino
sentence=An eTamil program compiled by artino.
paragraph=Built by LLVM; linked as a precompiled library.
category=Other
url=https://etamil.in
architectures=*
precompiled=true
ldflags=-lartino_prog
";

const LIBRARY_HEADER: &str = "// Generated by etamil --artino. The entry points of the compiled program.
#pragma once
#ifdef __cplusplus
extern \"C\" {
#endif
void artino_setup(void);
void artino_loop(void);
#ifdef __cplusplus
}
#endif
";

/// A sketch name arduino-cli accepts, from the program's file name: letters,
/// digits and underscores, starting with a letter.
pub fn sketch_name(program: &Path) -> String {
    let stem = program.file_stem().and_then(|s| s.to_str()).unwrap_or("program");
    let cleaned: String = stem
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' })
        .collect();
    format!("artino_{}", cleaned.trim_matches('_'))
}

fn ino(board: &Board, source_name: &str) -> String {
    format!(
        "// Generated by etamil --artino from {source} for {board} ({fqbn}).
// The program is in libartino_prog; this only starts it.
#include <artino_prog.h>
#include \"artino.h\"

void setup() {{
  Serial.begin(115200);
  artino_setup();
}}

void loop() {{
  artino_loop();
}}
",
        source = source_name,
        board = board.name,
        fqbn = board.fqbn
    )
}

/// A GNU ar archive holding `object` under `member`, with a symbol index
/// naming `symbols`. The index is what a linker reads to find the member.
pub fn archive(member: &str, object: &[u8], symbols: &[&str]) -> Vec<u8> {
    fn header(name: &str, size: usize) -> Vec<u8> {
        let text = format!("{:<16}{:<12}{:<6}{:<6}{:<8}{:<10}`\n", name, 0, 0, 0, 644, size);
        text.into_bytes()
    }
    fn pad(bytes: &mut Vec<u8>) {
        if bytes.len() % 2 == 1 {
            bytes.push(b'\n');
        }
    }

    let member_name = format!("{}/", member);
    // Index: count, one big-endian offset per symbol, then NUL-terminated names.
    let names_len: usize = symbols.iter().map(|s| s.len() + 1).sum();
    let index_len = 4 + 4 * symbols.len() + names_len;
    let index_padded = index_len + index_len % 2;
    let member_offset = 8 + 60 + index_padded;

    let mut out = b"!<arch>\n".to_vec();
    out.extend(header("/", index_len));
    out.extend((symbols.len() as u32).to_be_bytes());
    for _ in symbols {
        out.extend((member_offset as u32).to_be_bytes());
    }
    for symbol in symbols {
        out.extend(symbol.as_bytes());
        out.push(0);
    }
    pad(&mut out);
    out.extend(header(&member_name, object.len()));
    out.extend(object);
    pad(&mut out);
    out
}

/// Where a written sketch is: the folder arduino-cli builds, and the
/// libraries folder it must be given.
pub struct Written {
    pub sketch: PathBuf,
    pub libraries: PathBuf,
}

/// Write the sketch folder.
pub fn write(
    out: &Path,
    program: &Path,
    board: &Board,
    ports: [bool; 4],
    compiled: &Compiled,
    manifest: &Manifest,
    object: &[u8],
) -> io::Result<Written> {
    let name = sketch_name(program);
    let base = out.join(&name);
    let sketch = base.join(&name);
    fs::create_dir_all(&sketch)?;
    let source_name = program.file_name().and_then(|s| s.to_str()).unwrap_or("program.qmz");
    fs::write(sketch.join(format!("{}.ino", name)), ino(board, source_name))?;
    fs::write(sketch.join("artino.h"), RUNTIME_HEADER)?;
    fs::write(sketch.join("artino_rt.cpp"), RUNTIME_SOURCE)?;
    fs::write(sketch.join("artino_config.h"), config(ports, board, manifest, compiled.tone))?;
    if *manifest != Manifest::default() {
        fs::write(sketch.join("artino_shims.cpp"), manifest::shims(manifest, source_name))?;
    }
    fs::write(sketch.join("artino_sites.txt"), site_list(source_name, &compiled.sites))?;

    let libraries = base.join("libraries");
    let library = libraries.join("artino_prog");
    let objects = library.join("src").join(board.mcu);
    fs::create_dir_all(&objects)?;
    fs::write(library.join("library.properties"), LIBRARY_PROPERTIES)?;
    fs::write(library.join("src").join("artino_prog.h"), LIBRARY_HEADER)?;
    fs::write(objects.join("libartino_prog.a"), archive("prog.o", object, EXPORTS))?;
    Ok(Written { sketch, libraries })
}

/// Every report site by number: what a board with `line_reports` means by
/// `#17`, and on any board the list of where the program can differ from the VM.
fn site_list(source_name: &str, sites: &[String]) -> String {
    let mut text = format!("// artino report sites in {}: the number a report gives, and where it is.\n", source_name);
    for (index, place) in sites.iter().enumerate() {
        text.push_str(&format!("#{}\t{}\n", index, place.replace('\n', " ")));
    }
    text
}

/// The ports the program opens and the board has; the runtime builds in only
/// those. A port chosen at run time counts as any, so the board's own count
/// is what keeps an Uno from carrying buffers for ports it lacks.
fn config(ports: [bool; 4], board: &Board, manifest: &Manifest, tone: bool) -> String {
    let mut text = String::from("// Written by etamil --artino: the serial ports this program opens, and how it reports.\n");
    for (port, used) in ports.iter().enumerate().skip(1) {
        let built = *used && (port < board.serial_ports as usize || manifest.ports.iter().any(|(n, _)| *n as usize == port));
        text.push_str(&format!("#define ARTINO_PORT{} {}\n", port, built as u8));
    }
    // A report as a line, a number and a word: see Board::line_reports.
    text.push_str(&format!("#define ARTINO_LINE_REPORTS {}\n", board.line_reports as u8));
    // Tone only when the program makes one (emit::Compiled::tone).
    text.push_str(&format!("#define ARTINO_TONE {}\n", tone as u8));
    text
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn archive_index_points_at_the_member_header() {
        let object = b"\x7fELFsomething";
        let ar = archive("prog.o", object, EXPORTS);
        assert!(ar.starts_with(b"!<arch>\n/               "));
        let count = u32::from_be_bytes(ar[68..72].try_into().unwrap());
        assert_eq!(count, 2);
        let offset = u32::from_be_bytes(ar[72..76].try_into().unwrap()) as usize;
        assert_eq!(&ar[offset..offset + 7], b"prog.o/");
        assert_eq!(&ar[offset + 60..offset + 60 + object.len()], object);
        assert_eq!(ar.len() % 2, 0);
    }

    #[test]
    fn sketch_names_are_what_arduino_cli_accepts() {
        assert_eq!(sketch_name(Path::new("dir/kaNu.qmz")), "artino_kaNu");
        assert_eq!(sketch_name(Path::new("blink-2.qmz")), "artino_blink_2");
    }
}
