#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Mohammed Maruff (Esan Maruff) <esan@etamil.in>
#
# Keep etamil-textmate/ in step with the editor support the compiler generates.
#
# The grammar is generated by scripts/generate_editor_support.py from the
# lexer's keyword tables and lives in the VS Code extension's repository; this
# bundle carries a copy so JetBrains users have one folder to import. The copy
# would drift silently the first time a keyword is added, so run this after
# regenerating, and in CI with --check.
#
#   packaging/jetbrains/sync-bundle.sh /path/to/eTamil_vsCode           # update
#   packaging/jetbrains/sync-bundle.sh /path/to/eTamil_vsCode --check   # exit 1 if stale
set -euo pipefail

EXT="${1:?usage: sync-bundle.sh <eTamil_vsCode checkout> [--check]}"
MODE="${2:-}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUNDLE="$HERE/etamil-textmate"

pairs=(
    "$EXT/syntaxes/etamil.tmLanguage.json|$BUNDLE/syntaxes/etamil.tmLanguage.json"
    "$EXT/language-configuration.json|$BUNDLE/language-configuration.json"
)

stale=0
for pair in "${pairs[@]}"; do
    src="${pair%%|*}"
    dest="${pair##*|}"
    [ -f "$src" ] || { echo "not found: $src" >&2; exit 1; }
    if [ "$MODE" = "--check" ]; then
        # Compare without line endings: a Windows checkout may have CRLF.
        if ! diff -q <(tr -d '\r' < "$src") <(tr -d '\r' < "$dest") >/dev/null; then
            echo "stale: ${dest#"$HERE"/}" >&2
            stale=1
        fi
    else
        cp "$src" "$dest"
        echo "updated ${dest#"$HERE"/}"
    fi
done

if [ "$MODE" = "--check" ]; then
    [ "$stale" -eq 0 ] && echo "the JetBrains bundle is current"
    exit "$stale"
fi
