#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Mohammed Maruff (Esan Maruff) <esan@etamil.in>
"""Type-check the LLVM backend on a machine that cannot build LLVM.

`src/codegen.rs` is behind `--features llvm`, which needs `llvm-sys 180`, which
needs LLVM 18 installed and is Linux/macOS only. So on Windows the file cannot
be compiled at all — and it has broken three times without anyone noticing,
twice because an AST node grew a field and the pattern in codegen.rs was left
naming too few.

But it can be *type-checked* anywhere, because llvm-sys's own source sits in the
cargo registry cache even where it cannot be compiled. This generates a
signature-only crate from that source — the same declarations, no library behind
them — points cargo at it, and runs `cargo check --features llvm`.

    python scripts/check_llvm_backend.py
    python scripts/check_llvm_backend.py --clean     # if it was interrupted

The shim is generated from every llvm-sys module this repository uses, found by
reading the imports rather than from a list. It was `core` and the crate root
for a long time, and then `src/artino/emit.rs` arrived using `target`,
`target_machine`, `analysis`, `error` and `transforms::pass_builder` -- and the
script stopped working everywhere, including on Ubuntu, while
`docs/CONTINUATION.md` went on saying it worked on Windows. A hardcoded list of
modules goes stale exactly the way the hardcoded list of *sources* above it
already did once.

What this catches: every type error and every borrow error, in the whole file.
What it cannot catch: invalid IR, and a wrong answer. Those need Ubuntu and
`scripts/run_parity.sh`. Do not read a clean run here as "the backend works".

It is not a substitute for the `llvm-backend` CI job, which builds against the
real library. It is what makes the file editable on a machine that job does not
run on.
"""

import argparse
import glob
import io
import os
import re
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CRATE = os.path.join(ROOT, "etamil_compiler")
SHIM = os.path.join(CRATE, "target", "llvm-sys-shim")
CONFIG_DIR = os.path.join(CRATE, ".cargo")
CONFIG = os.path.join(CONFIG_DIR, "config.toml")
LOCK = os.path.join(CRATE, "Cargo.lock")
LOCK_BACKUP = os.path.join(CRATE, "target", "Cargo.lock.before-llvm-check")

# The only two files that touch llvm-sys.
# Every source that names an LLVM symbol, found rather than listed: a hardcoded
# list goes stale silently, and this one did — src/fileio/csv_handler.rs was
# deleted and the script then crashed on a missing file instead of checking
# anything.
def llvm_sources():
    found = []
    for base, _, files in os.walk(os.path.join(CRATE, "src")):
        for name in files:
            if not name.endswith(".rs"):
                continue
            path = os.path.join(base, name)
            with io.open(path, encoding="utf-8") as handle:
                if "llvm_sys" in handle.read():
                    found.append(path)
    return sorted(found)

# Type aliases and enums the declarations refer to. Over-broad on purpose: an
# alias nothing uses costs nothing, and a missing one is a confusing error.
ALIASES = [
    "LLVMContextRef", "LLVMModuleRef", "LLVMBuilderRef", "LLVMValueRef",
    "LLVMTypeRef", "LLVMBasicBlockRef", "LLVMMetadataRef", "LLVMNamedMDNodeRef",
    "LLVMUseRef", "LLVMAttributeRef", "LLVMDiagnosticInfoRef", "LLVMComdatRef",
    "LLVMModuleFlagEntry", "LLVMValueMetadataEntry", "LLVMOperandBundleRef",
    "LLVMJITEventListenerRef",
]

ENUMS = [
    "LLVMIntPredicate", "LLVMRealPredicate", "LLVMLinkage", "LLVMOpcode",
    "LLVMTypeKind", "LLVMVisibility", "LLVMUnnamedAddr", "LLVMDLLStorageClass",
    "LLVMCallConv", "LLVMValueKind", "LLVMAtomicOrdering", "LLVMAtomicRMWBinOp",
    "LLVMDiagnosticSeverity", "LLVMInlineAsmDialect", "LLVMModuleFlagBehavior",
    "LLVMThreadLocalMode", "LLVMTailCallKind", "LLVMGEPNoWrapFlags",
]

# llvm-sys features etamil_compiler asks for. Cargo refuses a path override that
# does not offer them, so the shim has to declare them even though they do
# nothing here.
FEATURES = [
    "prefer-dynamic", "no-llvm-linking", "strict-versioning",
    "disable-alltargets-init", "force-static", "force-dynamic",
]

CARGO_TOML = (
    '# Generated by scripts/check_llvm_backend.py. Not part of the build.\n'
    '[package]\nname = "llvm-sys"\nversion = "180.0.0"\nedition = "2021"\n\n'
    '[lib]\nname = "llvm_sys"\npath = "src/lib.rs"\n\n'
    "[features]\n" + "".join("%s = []\n" % f for f in FEATURES) + "\n"
    '[dependencies]\nlibc = "0.2"\nanyhow = "1"\n'
)


def find_llvm_sys():
    found = glob.glob(os.path.expanduser("~/.cargo/registry/src/*/llvm-sys-180.*"))
    if not found:
        sys.exit(
            "llvm-sys 180 is not in the cargo registry cache, so there are no\n"
            "signatures to copy. Run `cargo fetch` in etamil_compiler first."
        )
    return sorted(found)[-1]


def symbols_used():
    names = set()
    for path in llvm_sources():
        text = io.open(path, encoding="utf-8").read()
        names.update(re.findall(r"\bLLVM[A-Za-z0-9_]+", text))
    return names


def module_path(relative):
    """`target_machine.rs` -> `target_machine`; `transforms/pass_builder.rs` ->
    `transforms::pass_builder`; `lib.rs` -> the crate root."""
    parts = relative.replace("\\", "/").split("/")
    if parts[-1] == "mod.rs":
        parts = parts[:-1]
    else:
        parts[-1] = parts[-1][:-3]
    if parts == ["lib"]:
        return ""
    return "::".join(parts)


def read_llvm_modules(source):
    """Every llvm-sys module, as (module path -> its source text)."""
    root = os.path.join(source, "src")
    modules = {}
    for base, _, files in os.walk(root):
        for name in files:
            if not name.endswith(".rs"):
                continue
            full = os.path.join(base, name)
            relative = os.path.relpath(full, root)
            modules[module_path(relative)] = io.open(full, encoding="utf-8").read()
    return modules


DECLARATION = re.compile(r"pub fn (LLVM\w+)\((?:[^;]*?)\)(?:\s*->\s*[^;]+?)?;", re.S)


def generate(source):
    modules = read_llvm_modules(source)
    lib = modules.get("", "")
    wanted = symbols_used()

    # Where each function is declared, and what it looks like.
    declarations = {}
    home = {}
    for path, text in sorted(modules.items()):
        for match in DECLARATION.finditer(text):
            name = match.group(1)
            if name not in declarations:
                declarations[name] = match.group(0)
                home[name] = path

    keep = {name for name in wanted if name in declarations}
    # A signature may name another declared function as a callback parameter.
    for _ in range(3):
        for name in list(keep):
            for other in re.findall(r"\bLLVM\w+", declarations[name]):
                if other in declarations:
                    keep.add(other)

    # Types: the aliases and enums named by anything kept, plus the ones listed
    # below. Every one is emitted at the crate root and re-exported from the
    # module llvm-sys declares it in, so both `llvm_sys::LLVMLinkage` and
    # `llvm_sys::target::LLVMTargetDataRef` resolve without the shim having to
    # model llvm-sys's own `use` graph.
    mentioned = set(ALIASES) | set(ENUMS)
    for name in keep:
        mentioned.update(re.findall(r"\bLLVM\w+", declarations[name]))
    mentioned.update(wanted)
    # The header writes LLVMBool itself, so collecting llvm-sys's own
    # declaration of it defines the name twice.
    mentioned.discard("LLVMBool")

    aliases = {}
    enums = {}
    for path, text in sorted(modules.items()):
        for name in sorted(mentioned):
            if name in aliases or name in enums:
                continue
            alias = re.search(r"pub type %s = [^;]+;" % name, text)
            if alias:
                aliases[name] = (path, alias.group(0).replace("super::", ""))
                continue
            enum = re.search(r"pub enum %s \{.*?\n\}" % name, text, re.S)
            if enum:
                enums[name] = (path, enum.group(0))

    opaque = sorted(
        {
            found.group(1)
            for _, body in aliases.values()
            for found in [re.search(r"\*mut (\w+)", body)]
            if found
        }
    )

    out = [
        "//! A stand-in for llvm-sys 180: the same signatures, nothing behind them.",
        "//!",
        "//! Generated by scripts/check_llvm_backend.py from llvm-sys's own source, so",
        "//! it cannot disagree with the real crate about a signature. Never committed,",
        "//! never linked, and it would not run if it were.",
        "#![allow(non_snake_case, non_camel_case_types, dead_code)]",
        "",
        "pub type LLVMBool = ::libc::c_int;",
    ]
    out += ["pub enum %s {}" % name for name in opaque]
    out += [""]
    out += [body for _, body in sorted(aliases.values())]
    out += [""]
    out += [
        "#[repr(C)]\n#[derive(Clone, Copy, Debug, PartialEq)]\n" + body
        for _, body in sorted(enums.values())
    ]
    out += [""]

    prelude = sorted(name for name in aliases if name in set(ALIASES))
    out += [
        "pub mod prelude {",
        "    pub use super::{LLVMBool, %s};" % ", ".join(prelude),
        "}",
        "",
    ]

    # One module per llvm-sys module that contributes something, nested where
    # llvm-sys nests them.
    used_modules = sorted({home[name] for name in keep} | {p for p, _ in aliases.values()}
                          | {p for p, _ in enums.values()})
    tree = {}
    for path in used_modules:
        if path == "":
            continue
        node = tree
        for part in path.split("::"):
            node = node.setdefault(part, {})

    def emit(node, prefix, depth):
        lines = []
        for part in sorted(node):
            here = (prefix + "::" + part) if prefix else part
            pad = "    " * depth
            lines.append("%spub mod %s {" % (pad, part))
            own_types = sorted(
                [n for n, (p, _) in aliases.items() if p == here]
                + [n for n, (p, _) in enums.items() if p == here]
            )
            if own_types:
                lines.append("%s    pub use crate::{%s};" % (pad, ", ".join(own_types)))
            own_functions = sorted(n for n in keep if home[n] == here)
            if own_functions:
                lines.append("%s    #[allow(unused_imports)]" % pad)
                lines.append("%s    use crate::prelude::*;" % pad)
                lines.append("%s    #[allow(unused_imports)]" % pad)
                lines.append("%s    use crate::*;" % pad)
                lines.append('%s    extern "C" {' % pad)
                for name in own_functions:
                    for line in declarations[name].splitlines():
                        lines.append(pad + "        " + line.strip())
                lines.append("%s    }" % pad)
            lines += emit(node[part], here, depth + 1)
            lines.append("%s}" % pad)
        return lines

    out += emit(tree, "", 0)
    out += [""]

    os.makedirs(os.path.join(SHIM, "src"), exist_ok=True)
    io.open(os.path.join(SHIM, "src/lib.rs"), "w", encoding="utf-8", newline="\n").write(
        "\n".join(out) + "\n"
    )
    io.open(os.path.join(SHIM, "Cargo.toml"), "w", encoding="utf-8", newline="\n").write(
        CARGO_TOML
    )

    # An enum variant is not a declaration and never will be: it arrives with
    # its enum. The test is against the emitted *bodies*, not the names they are
    # keyed by — `aliases` and `enums` are maps now, and checking the keys
    # quietly reported every variant as missing while the build was fine.
    bodies = [body for _, body in aliases.values()] + [body for _, body in enums.values()]
    missing = sorted(
        name
        for name in wanted
        if name not in declarations
        and name not in opaque
        and not any(name in body for body in bodies)
    )
    return len(keep), missing


def clean():
    """Put the checkout back. Cargo may rewrite Cargo.lock through an override."""
    if os.path.exists(CONFIG):
        os.remove(CONFIG)
    if os.path.isdir(CONFIG_DIR) and not os.listdir(CONFIG_DIR):
        os.rmdir(CONFIG_DIR)
    if os.path.exists(LOCK_BACKUP):
        shutil.copyfile(LOCK_BACKUP, LOCK)
        os.remove(LOCK_BACKUP)
    shutil.rmtree(SHIM, ignore_errors=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--clean",
        action="store_true",
        help="undo an interrupted run: remove the override and restore Cargo.lock",
    )
    arguments = parser.parse_args()

    if arguments.clean:
        clean()
        print("cleaned up.")
        return 0

    kept, missing = generate(find_llvm_sys())
    print("shim: %d declarations" % kept)
    if missing:
        # Not fatal: cargo will say exactly what is unresolved, which is a
        # better error than anything this script could invent.
        print("  not found in llvm-sys, expect an error naming it: %s" % ", ".join(missing))

    os.makedirs(CONFIG_DIR, exist_ok=True)
    shutil.copyfile(LOCK, LOCK_BACKUP)
    io.open(CONFIG, "w", encoding="utf-8", newline="\n").write(
        "# Generated by scripts/check_llvm_backend.py; deleted when it finishes.\n"
        'paths = ["%s"]\n' % SHIM.replace("\\", "/")
    )

    try:
        finished = subprocess.run(
            ["cargo", "check", "--features", "llvm", "--all-targets"],
            cwd=CRATE,
        )
    finally:
        clean()

    if finished.returncode == 0:
        print()
        print("Types check. That is not the same as working:")
        print("  the IR is unverified and the answers uncompared until")
        print("  scripts/run_parity.sh runs on Linux or macOS.")
    return finished.returncode


if __name__ == "__main__":
    sys.exit(main())
