#!/usr/bin/env python3
"""artino/b0/build.py — LLVM IR -> object -> precompiled Arduino library -> sketch -> board.

    python build.py                       # build for every board in BOARDS
    python build.py uno pico              # just these
    python build.py uno --upload COM5     # build and upload one board

This is the toolchain spike (B0 in docs/artino.md): it proves that code LLVM
emits for AVR and Cortex-M links against the Arduino cores, which are built by
gcc, and runs. Nothing here is the backend; codegen replaces prog.ll in B1.

Tools, found in this order:
  llc, llvm-ar   $ARTINO_LLVM_BIN, else Rust's own LLVM (rustup component add llvm-tools)
  arduino-cli    $ARDUINO_CLI, else PATH, else ~/tools/arduino-cli/
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
BUILD = HERE / "build"

# board -> (FQBN, LLVM triple, LLVM cpu)
BOARDS = {
    "uno": ("arduino:avr:uno", "avr", "atmega328p"),
    "nano": ("arduino:avr:nano", "avr", "atmega328p"),
    "mega": ("arduino:avr:mega", "avr", "atmega2560"),
    "pico": ("rp2040:rp2040:rpipico", "thumbv6m-none-eabi", "cortex-m0plus"),
    "pico2": ("rp2040:rp2040:rpipico2", "thumbv8m.main-none-eabi", "cortex-m33"),
}

LIBRARY_PROPERTIES = """name=artino_prog
version=0.0.1
author=eTamil artino
maintainer=eTamil artino
sentence=An eTamil program compiled by artino.
paragraph=Built by LLVM; linked as a precompiled library.
category=Other
url=https://etamil.in
architectures=*
precompiled=true
ldflags=-lartino_prog
"""

HEADER = """// Generated by artino. The entry points of a compiled eTamil program.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
void artino_setup(void);
void artino_loop(void);
#ifdef __cplusplus
}
#endif
"""


def run(cmd, **kw):
    print("  $", " ".join(str(c) for c in cmd))
    return subprocess.run([str(c) for c in cmd], check=True, text=True, **kw)


def llvm_bin():
    if os.environ.get("ARTINO_LLVM_BIN"):
        return Path(os.environ["ARTINO_LLVM_BIN"])
    sysroot = subprocess.run(["rustc", "--print", "sysroot"], capture_output=True, text=True, check=True).stdout.strip()
    host = next(line.split(": ")[1] for line in subprocess.run(
        ["rustc", "-vV"], capture_output=True, text=True, check=True).stdout.splitlines() if line.startswith("host: "))
    return Path(sysroot) / "lib" / "rustlib" / host / "bin"


def arduino_cli():
    """arduino-cli as a command prefix, with its config file when one is given.

    On Windows the Microsoft Store Python runs its child processes with a
    private copy of %LOCALAPPDATA%, so arduino-cli started from here would not
    see boards installed in AppData\\Local\\Arduino15. Keeping the Arduino data
    outside AppData and naming the config file avoids that: set
    $ARDUINO_CLI_CONFIG, or put it at ~/tools/arduino15/arduino-cli.yaml.
    """
    if os.environ.get("ARDUINO_CLI"):
        cli = os.environ["ARDUINO_CLI"]
    elif shutil.which("arduino-cli"):
        cli = shutil.which("arduino-cli")
    else:
        local = Path.home() / "tools" / "arduino-cli" / ("arduino-cli.exe" if os.name == "nt" else "arduino-cli")
        if not local.exists():
            sys.exit("arduino-cli not found: set ARDUINO_CLI or put it on PATH")
        cli = str(local)
    config = os.environ.get("ARDUINO_CLI_CONFIG") or Path.home() / "tools" / "arduino15" / "arduino-cli.yaml"
    return [cli, "--config-file", str(config)] if Path(config).exists() else [cli]


def exe(folder, name):
    path = folder / (name + (".exe" if os.name == "nt" else ""))
    if not path.exists():
        sys.exit(f"{path} not found: run `rustup component add llvm-tools` or set ARTINO_LLVM_BIN")
    return path


def board_mcu(cli, fqbn):
    """build.mcu, the folder name Arduino looks in for a precompiled library."""
    props = subprocess.run([*cli, "compile", "--fqbn", fqbn, "--show-properties", str(HERE / "sketch" / "artino_b0")],
                           capture_output=True, text=True, check=True).stdout
    for line in props.splitlines():
        if line.startswith("build.mcu="):
            return line.split("=", 1)[1].strip()
    sys.exit(f"no build.mcu for {fqbn}")


def build(board, upload_port=None):
    fqbn, triple, cpu = BOARDS[board]
    llvm, cli = llvm_bin(), arduino_cli()
    out = BUILD / board
    lib = out / "libraries" / "artino_prog"
    print(f"\n== {board}  ({fqbn}, {triple}/{cpu})")

    mcu = board_mcu(cli, fqbn)
    obj_dir = lib / "src" / mcu
    obj_dir.mkdir(parents=True, exist_ok=True)
    (lib / "library.properties").write_text(LIBRARY_PROPERTIES)
    (lib / "src" / "artino_prog.h").write_text(HEADER)

    obj = out / "prog.o"
    archive = obj_dir / "libartino_prog.a"
    run([exe(llvm, "llc"), f"-mtriple={triple}", f"-mcpu={cpu}", "-O2", "-filetype=obj",
         HERE / "prog.ll", "-o", obj])
    if archive.exists():
        archive.unlink()
    run([exe(llvm, "llvm-ar"), "rcs", archive, obj])

    cmd = [*cli, "compile", "--fqbn", fqbn, "--libraries", out / "libraries",
           "--build-path", out / "sketch-build", "--warnings", "default", HERE / "sketch" / "artino_b0"]
    if upload_port:
        cmd += ["--upload", "--port", upload_port]
    run(cmd)


def main():
    args = sys.argv[1:]
    port = None
    if "--upload" in args:
        i = args.index("--upload")
        port = args[i + 1]
        del args[i:i + 2]
    boards = args or [b for b in BOARDS if b != "pico2"]
    unknown = [b for b in boards if b not in BOARDS]
    if unknown:
        sys.exit(f"unknown board(s): {', '.join(unknown)}; known: {', '.join(BOARDS)}")
    if port and len(boards) != 1:
        sys.exit("--upload needs exactly one board")
    failed = []
    for board in boards:
        try:
            build(board, port)
        except subprocess.CalledProcessError:
            failed.append(board)
    print("\nB0:", "all built" if not failed else "FAILED: " + ", ".join(failed))
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
